from db_config import DB_CONFIG
import asyncio
import psycopg2
from psycopg2.extras import execute_values
import traceback
from datetime import datetime
from nepse import AsyncNepse

def setup_db(conn):
    cur = conn.cursor()
    # Ensure system_notifications table exists
    cur.execute('''
        CREATE TABLE IF NOT EXISTS system_notifications (
            id SERIAL PRIMARY KEY,
            type VARCHAR(30) NOT NULL DEFAULT 'info',
            title VARCHAR(255) NOT NULL,
            message TEXT,
            source VARCHAR(100),
            is_read BOOLEAN DEFAULT FALSE,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
    ''')
    conn.commit()
    cur.close()

def send_notification(conn, title, message='', type='info', source='nepse_companies.py'):
    try:
        cur = conn.cursor()
        cur.execute('''
            INSERT INTO system_notifications (type, title, message, source, is_read)
            VALUES (%s, %s, %s, %s, FALSE)
        ''', (type, title, message, source))
        conn.commit()
        cur.close()
        print(f"Notification Sent: [{type.upper()}] {title} - {message}")
    except Exception as e:
        conn.rollback()
        print(f"Failed to save system notification: {e}")

def store_companies(conn, companies):
    if not companies:
        print("No companies to store.")
        return

    cur = conn.cursor()

    # Ensure the table exists with the specified schema
    cur.execute('''
        CREATE TABLE IF NOT EXISTS "public"."companies" (
            "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            "company_name" character varying(255),
            "symbol" character varying(50),
            "nepse_id" integer,
            "security_name" character varying(255),
            "status" character varying(10),
            "company_email" character varying(255),
            "website" character varying(255),
            "sector_name" character varying(255),
            "regulatory_body" character varying(255),
            "instrument_type" character varying(255),
            "instrument" character varying(50),
            "face_value" integer,
            "listed_shares" bigint,
            "total_value" bigint,
            CONSTRAINT "companies_pkey" PRIMARY KEY ("id")
        )
    ''')

    # Ensure unique constraint on symbol for upsert
    cur.execute('''
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace 
                WHERE c.relname = 'companies_symbol' AND n.nspname = 'public'
            ) THEN
                CREATE UNIQUE INDEX companies_symbol ON public.companies USING btree (symbol);
            END IF;
        END $$;
    ''')

    # Fetch existing companies to detect new ones and status changes
    cur.execute("SELECT symbol, status, company_name FROM companies WHERE symbol IS NOT NULL")
    existing_companies = {row[0]: {'status': row[1], 'name': row[2]} for row in cur.fetchall()}

    values = []
    skipped = 0
    new_companies = []
    status_changes = []

    for c in companies:
        symbol = c.get('symbol', c.get('Symbol', ''))
        if not symbol:
            skipped += 1
            continue
            
        name = c.get('companyName', '')
        status = c.get('status', '')

        # Detect changes
        if symbol not in existing_companies:
            new_companies.append(f"{symbol} ({name})")
        else:
            old_status = existing_companies[symbol]['status']
            if old_status != status:
                status_changes.append(f"{symbol}: {old_status} -> {status}")

        values.append((
            name,
            symbol,
            c.get('id'),
            c.get('securityName', ''),
            status,
            c.get('companyEmail', ''),
            c.get('website', ''),
            c.get('sectorName', ''),
            c.get('regulatoryBody', ''),
            c.get('instrumentType', ''),
            c.get('instrument', ''),
            c.get('faceValue'),
            c.get('listedShares'),
            c.get('totalValue'),
        ))

    if not values:
        print("No valid company records with symbol to upsert.")
        if skipped:
            print(f"(Skipped {skipped} records without symbol)")
        return

    insert_query = '''
        INSERT INTO companies (
            company_name, symbol, nepse_id, security_name, status,
            company_email, website, sector_name, regulatory_body,
            instrument_type, instrument, face_value, listed_shares, total_value
        )
        VALUES %s
        ON CONFLICT (symbol) DO UPDATE SET
            company_name = EXCLUDED.company_name,
            nepse_id = EXCLUDED.nepse_id,
            security_name = EXCLUDED.security_name,
            status = EXCLUDED.status,
            company_email = EXCLUDED.company_email,
            website = EXCLUDED.website,
            sector_name = EXCLUDED.sector_name,
            regulatory_body = EXCLUDED.regulatory_body,
            instrument_type = EXCLUDED.instrument_type,
            instrument = EXCLUDED.instrument,
            face_value = EXCLUDED.face_value,
            listed_shares = EXCLUDED.listed_shares,
            total_value = EXCLUDED.total_value
    '''

    execute_values(cur, insert_query, values)
    conn.commit()

    cur.execute("SELECT COUNT(*) FROM companies")
    total = cur.fetchone()[0]

    # Dispatch notifications for new companies
    for nc in new_companies:
        send_notification(
            conn,
            title=f"New company listed: {nc.split(' (')[0]}",
            message=f"Company {nc} has been added to the database.",
            type='info'
        )
        
    # Dispatch notifications for status changes
    for sc in status_changes:
        send_notification(
            conn,
            title=f"Company status changed",
            message=f"Status update: {sc}",
            type='warning'
        )

    # General completion notification
    send_notification(
        conn,
        title="Company list updated from NEPSE",
        message=f"Fetched and upserted {len(values)} companies. {len(new_companies)} new, {len(status_changes)} status changes. Total in DB: {total}.",
        type='success'
    )

    print(f"Upserted {len(values)} companies (skipped {skipped}). Total in DB: {total}")
    cur.close()

def populate_chukul_details(conn):
    print("Fetching Chukul symbol database details...")
    import requests
    import warnings
    from urllib3.exceptions import InsecureRequestWarning
    
    # Suppress certificate verification warnings
    warnings.filterwarnings('ignore', category=InsecureRequestWarning)
    
    url = "https://chukul.com/api/data/symbol/"
    try:
        response = requests.get(url, verify=False, timeout=30)
        response.raise_for_status()
        data = response.json()
        
        cur = conn.cursor()
        
        # Ensure the columns exist in companies table
        print("Checking/creating Chukul columns in companies table...")
        cur.execute('''
            ALTER TABLE companies ADD COLUMN IF NOT EXISTS chukul_id INTEGER DEFAULT NULL;
            ALTER TABLE companies ADD COLUMN IF NOT EXISTS chukul_sector_id INTEGER DEFAULT NULL;
        ''')
        conn.commit()
        
        # Prepare updates
        updated_count = 0
        print(f"Loaded {len(data)} symbol entries from Chukul API. Populating table...")
        for item in data:
            c_id = item.get('id')
            c_sec_id = item.get('sector_id')
            symbol = item.get('symbol')
            
            if symbol and c_id is not None:
                cur.execute('''
                    UPDATE companies 
                    SET chukul_id = %s, chukul_sector_id = %s 
                    WHERE symbol = %s;
                ''', (c_id, c_sec_id, symbol))
                updated_count += cur.rowcount
                
        conn.commit()
        cur.close()
        print(f"Successfully populated Chukul details for {updated_count} companies.")
        
    except Exception as e:
        print(f"Error fetching/populating Chukul data: {e}")

async def fetch_and_store_companies():
    print("Connecting to database...")
    conn = psycopg2.connect(**DB_CONFIG)
    setup_db(conn)
    
    send_notification(
        conn,
        title="Company list scraper started",
        message="Starting NEPSE company list extraction (Selenium-free).",
        type="scraper"
    )

    try:
        nepse = AsyncNepse()
        nepse.setTLSVerification(False)
        
        print("Authenticating with NEPSE...")
        await nepse.getMarketStatus()
        print("Successfully authenticated.")
        
        print("Fetching company list from NEPSE API...")
        companies = await nepse.getCompanyList()

        if companies:
            sample = companies[0]
            print(f"\nSample company data keys: {list(sample.keys())}")
            sample_symbol = sample.get('symbol', sample.get('Symbol', 'N/A'))
            sample_name = sample.get('companyName', sample.get('Company Name', 'N/A'))
            print(f"Sample: symbol={sample_symbol}, name={sample_name}\n")

            store_companies(conn, companies)
            populate_chukul_details(conn)
        else:
            print("No company data retrieved.")
            send_notification(
                conn,
                title="Company list scraper failed",
                message="No company data retrieved from NEPSE API.",
                type="error"
            )
            
    except Exception as e:
        error_msg = traceback.format_exc()
        print(error_msg)
        send_notification(
            conn,
            title="Company list scraper error",
            message=f"An exception occurred: {str(e)}",
            type="error"
        )
    finally:
        await nepse.client.aclose()
        conn.close()

if __name__ == '__main__':
    asyncio.run(fetch_and_store_companies())
